name: MyCICDAction

on:
    Push:       
    branches: [ main ]
        

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Install .net core 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: restore and run
        run: dotnet restore

      - name: build app
        run: dotnet build -c Release --no-restore
