name: MyCICDAction

on:
    Push:       
    branches: [ main ]
        

jobs:
  build:
<<<<<<< HEAD
    runs-on: ubuntu-latest
     
=======
    runs-on: ubuntu-latest 
    
>>>>>>> c0c88eedc5d0815be2d38b3c6941c956e4e9bd70
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Install .net core 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: restore and run
        run: dotnet restore

      - name: build app
        run: dotnet build -c Release --no-restore
