name: MyCICDAction

on:
  push:       
    branches: [ main ]
        
  #workflow_dispatch:
  #Coomented above line

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Install .net core 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: restore and run
        run: dotnet restore AspNetCoreWebApi/AspNetCoreWebApi.sln

      - name: build app
        run: dotnet build AspNetCoreWebApi/AspNetCoreWebApi.sln -c Release --no-restore

      - name: run tests now
        run: dotnet test MyTestProject.Tests -c Release --no-build
